# Generated by Django 2.2.4 on 2019-08-22 13:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# home.migrations.0002_create_homepage

class Migration(migrations.Migration):

    replaces = [('home', '0001_initial'), ('home', '0002_create_homepage'), ('home', '0003_auto_20190711_1250')]

    initial = True

    dependencies = [
        ('series', '0001_initial'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0040_page_draft_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RunPython(
            code=home.migrations.0002_create_homepage.create_homepage,
            reverse_code=home.migrations.0002_create_homepage.remove_homepage,
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='promoted_series_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sub_title',
            field=models.CharField(default='Temp', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HomePageSeriesPreviewsOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_previews', to='home.HomePage')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.SeriesPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomePagePromotedSeriesOrderable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_series', to='home.HomePage')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.SeriesPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
