# Generated by Django 2.2.3 on 2019-07-05 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190705_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepromotedseriesorderable',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.SeriesPage'),
        ),
        migrations.AlterField(
            model_name='homepageseriespreviewsorderable',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.SeriesPage'),
        ),
    ]
