# Generated by Django 2.2.5 on 2019-10-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepagepromotedmoviesorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagepromotedmoviesorderable',
            name='title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='promoted_movies_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
