# Generated by Django 2.2.3 on 2019-07-05 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190705_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagepromotedseriesorderable',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
