# Generated by Django 2.2.3 on 2019-07-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepagepromotedseriesorderable_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagepromotedseriesorderable',
            name='title',
        ),
        migrations.AddField(
            model_name='homepage',
            name='promoted_series_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
