# Generated by Django 2.2.7 on 2019-11-08 07:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20191104_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='promoted_series_title',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('promoted_series', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted series block', required=False)), ('series', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False)))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HomePagePromotedSeriesOrderable',
        ),
    ]
