# Generated by Django 2.2.7 on 2019-11-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20191108_0939'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSeriesPreviewsOrderable',
        ),
    ]
