# Generated by Django 2.2.7 on 2019-11-08 07:55

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_delete_homepageseriespreviewsorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='promoted_movies_title',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('promoted_series', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted series block', required=False)), ('series', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False)))])), ('series_preview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the series preview block', required=False)), ('series', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False))])), ('promoted_movies', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted movies block', required=False)), ('movies', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Movies', page_type=['movie.MoviePage'], required=False)))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HomePagePromotedMoviesOrderable',
        ),
    ]
