# Generated by Django 2.2.7 on 2019-11-08 08:38

from django.db import migrations
import video.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20191108_0955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='promoted_videos_sub_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='promoted_videos_title',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('promoted_series', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted series block', required=False)), ('series', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False)))])), ('series_preview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the series preview block', required=False)), ('series', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False))])), ('promoted_movies', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted movies block', required=False)), ('movies', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Movies', page_type=['movie.MoviePage'], required=False)))])), ('promoted_videos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted videos block', required=False)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Sub title for the promoted videos block', required=False)), ('movies', wagtail.core.blocks.ListBlock(video.blocks.VideoChooserBlock(label='Videos', required=False)))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='HomePagePromotedVideosOrderable',
        ),
    ]
