# Generated by Django 2.2.7 on 2019-11-08 09:34

from django.db import migrations
import video.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20191108_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('promoted_series', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted series block', required=False)), ('disable_info', wagtail.core.blocks.BooleanBlock(help_text='Disable the display of series info (visible as default)', required=False)), ('series', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False)))])), ('series_preview', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the series preview block', required=False)), ('series', wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False))])), ('promoted_movies', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted movies block', required=False)), ('movies', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Movies', page_type=['movie.MoviePage'], required=False)))])), ('promoted_videos', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted videos block', required=False)), ('sub_title', wagtail.core.blocks.CharBlock(help_text='Sub title for the promoted videos block', required=False)), ('videos', wagtail.core.blocks.ListBlock(video.blocks.VideoChooserBlock(label='Videos', required=False)))]))], blank=True, null=True),
        ),
    ]
