# Generated by Django 2.2.5 on 2019-09-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformationsettings',
            options={'verbose_name': 'Contact Information'},
        ),
    ]
