# Generated by Django 2.2.3 on 2019-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seriesepisode',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='seriesepisode',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
