# Generated by Django 2.2.5 on 2019-09-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_squashed_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesepisode',
            name='isNew',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='seriesindexpage',
            name='sub_title',
            field=models.CharField(max_length=255),
        ),
    ]
