# Generated by Django 2.2.3 on 2019-07-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='produced_to',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
