# Generated by Django 2.2.5 on 2019-09-06 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20190906_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seriesepisode',
            old_name='isNew',
            new_name='is_new',
        ),
    ]
