# Generated by Django 2.2.3 on 2019-07-12 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20190712_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriespage',
            name='hero',
            field=models.ForeignKey(blank=True, help_text='The hero image is used in the page header as well as in the information description of the series.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='seriespage',
            name='poster',
            field=models.ForeignKey(blank=True, help_text='The poster image is used in some promotional listings of the series.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
