# Generated by Django 2.2.3 on 2019-07-12 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_auto_20190712_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriespagerelatedseries',
            name='series',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='series.SeriesPage'),
        ),
    ]
