# Generated by Django 2.2.3 on 2019-07-12 09:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_auto_20190712_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriespagerelatedseries',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_series', to='series.SeriesPage'),
        ),
        migrations.AlterField(
            model_name='seriespagerelatedseries',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.SeriesPage'),
        ),
    ]
