# Generated by Django 2.2.7 on 2019-11-08 09:30

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0005_seriespage_multi_season_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seriespage',
            name='related_series_title',
        ),
        migrations.AddField(
            model_name='seriespage',
            name='content',
            field=wagtail.core.fields.StreamField([('related_series', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Title for the promoted series block', required=False)), ('series', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(can_choose_root=False, label='Series', page_type=['series.SeriesPage'], required=False)))]))], blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SeriesPageRelatedSeries',
        ),
    ]
