# Generated by Django 2.2.3 on 2019-07-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('series', '0007_remove_seriesepisode_episode_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriesindexpage',
            name='hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='seriesindexpage',
            name='sub_title',
            field=models.CharField(default='Temp', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SeriesIndexOrderable',
        ),
    ]
