# Generated by Django 2.2.3 on 2019-07-04 09:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.search.index


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, editable=False, max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Video Categories',
            },
        ),
        migrations.CreateModel(
            name='VideoType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('series', 'Series'), ('movie', 'Movie')], max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Media Types',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_video_id', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('video_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='video.VideoType')),
            ],
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
