# Generated by Django 2.2.5 on 2019-10-20 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_squashed_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
