# Generated by Django 2.2.3 on 2019-07-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20190705_0808'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoType',
        ),
        migrations.AlterModelOptions(
            name='videocategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Video Categories'},
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_type',
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(blank=True, to='video.VideoCategory'),
        ),
    ]
