# Generated by Django 2.2.3 on 2019-07-12 07:52

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20190712_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='video.VideoTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
