# Generated by Django 2.2.3 on 2019-07-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_auto_20190712_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.DurationField(blank=True, help_text='Insert duration either as minutes, e.g. `127` or as a time string e.g. `2:07`.', null=True),
        ),
    ]
